M48
; DRILL file {KiCad (6.0.5)} date So 29 Mai 2022 19:21:11 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-29T19:21:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
%
G90
G05
T1
X134.635Y-119.3
X139.715Y-118.284
X139.715Y-120.316
T2
X106.2Y-123.8
X162.1Y-117.1
T3
X103.5Y-103.5
X103.5Y-126.5
X161.5Y-103.5
X161.5Y-126.5
T0
M30
